### ISSUE TITLE
code-server 3.2 is incompatible with this repository

### ISSUE THREAD

**Issue by akhmerov** [betatim/vscode-binder#12]
Just a heads up:

code-server 3.2 was freshly released on conda-forge, and unless I did something very silly, it will break the repo quite dramatically

![image](https://user-images.githubusercontent.com/2069677/81020406-0718d680-8e69-11ea-93f6-e33ba87a0816.png)

that's what I see in the server logs.
```
Error: Cannot find module '/share/code-server/out/node/entry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Not sure if this is the best place to report, but it seems to be useful to pin to an older version in the interim.

**Comment by betatim** [comment]
If I start a fresh copy of this repo via https://mybinder.org/v2/gh/betatim/vscode-binder/betatim-patch-1 and then launch code-server it works.

This is a screenshot of the version of code-server. Is this also the "version" you see with 3.2? It seems non obvious if this is v3.2 or not.

<img width="661" alt="Screenshot 2020-05-05 at 09 43 42" src="https://user-images.githubusercontent.com/1448859/81044957-8d5b0a00-8eb5-11ea-9936-cf63219d241c.png">

**Comment by akhmerov** [comment]
You're right, it works. I'll need to check my setup, sorry for the noise.

**Comment by betatim** [comment]
No problem.
