### ISSUE TITLE
Factor out a conda package

### ISSUE THREAD

**Issue by nthiery** [betatim/vscode-binder#13]
This VS Code integration is amazing! I am setting it up for our local jupyterhub.

Could a conda (pip?) package be factored out of this repository so that one would just
need to mention it in one's environment.yml? The package would take care of:
- Listing the dependencies
- Providing the vscode proxy
- Running what's currently in the postBuild script

**Comment by betatim** [comment]
There should already be a conda package: https://github.com/betatim/vscode-binder/issues/3

**Comment by nthiery** [comment]
Hi Tim,

> https://github.com/betatim/vscode-binder/issues/3

Ah I had missed this! That's indeed a good first step, thanks. There
thus just remains the dependency (code-server) and postBuild part that
could be factored out. Which probably will take a conda package.

Happy to beta test one if someone gets to it. Alas I won't have time
soon myself for it.

**Comment by nthiery** [comment]
Just noticed a conda package already exists: https://anaconda.org/conda-forge/jupyter-vscode-proxy

Feedstock: https://github.com/conda-forge/jupyter-vscode-proxy-feedstock/tree/master/recipe

Seems to not go beyond installing the pip package. One more step nevertheless.

**Comment by nthiery** [comment]
#15 so that the next person finds the info I missed :-)

**Comment by xhochy** [comment]
`code-server` is also available as a conda package. I'm happily running this together in a single environment.

**Comment by nthiery** [comment]
Yes indeed; same here. My point is just about specifying the dependency between the two.

**Comment by xhochy** [comment]
> Yes indeed; same here. My point is just about specifying the dependency between the two.

I actually didn't do this yet as in some settings, I have both in different conda environments as `code-server` can be quiet picky about its node version.

**Comment by nthiery** [comment]
> I actually didn't do this yet as in some settings, I have both in
> different conda environments as `code-server` can be quiet picky
> about its node version.

Thanks for the feedback. This makes sense. I was also pondering about
it in case one would want to use e.g. VS codium instead of VS code for
better privacy (I assume here that code-server uses VS code; it would
be great to have it or some variant of the package use VS codium
instead).

**Comment by xhochy** [comment]
`code-server` has its own telemetry which you can disable with `--disable-telemetry`.

**Comment by nthiery** [comment]
> `code-server` has its own telemetry which you can disable with `--disable-telemetry`.

Ah, ah! Very good. Thanks for the tip!

**Comment by xhochy** [comment]
Seems like everything in this issue was solved, closing.
