### ISSUE TITLE
The installation of the ms-python.python fails

### ISSUE THREAD

**Issue by nthiery** [betatim/vscode-binder#14]
For information: the current postBuild script tries to install ms-python.python, and fails to do so:
```
code-server --install-extension ms-python.python
Installing extensions...
Extension 'ms-python.python' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-vscode.csharp
error undefined
```

It does not seem to matter much. I only stumbled on it because I was trying to replicate the postBuild script by a sequence of RUN commands in my Dockerfile.

**Comment by xhochy** [comment]
This happens when the version of code-server is too old and thus the extension incompatible with the version of VSCode packages in it. I guess the repo is cached with a too old version in Binder.

**Comment by nthiery** [comment]
> This happens when the version of code-server is too old and thus the
> extension incompatible with the version of VSCode packages in it. I
> guess the repo is cached with a too old version in Binder.

As data point: the other day when I created this issue the failure was
with a fresh conda install from conda-forge. Haven't retried since
then though.
