### ISSUE TITLE
postBuild error and unable to install extensions on setup

### ISSUE THREAD

**Issue by akielbowicz** [betatim/vscode-binder#23]
Hi,

I was trying to install additional extensions but the call to `code-server` is failing in the postBuild. If you check in vscode, from your repo binder example, it doesn't have the python extension installed. But you can install it from within vscode with no problem.

I can't debug the problem using the repo2docker on my current machine, but here is a minimal code example to reproduce the error

```bash
#!/bin/bash
set -ex
code-server --version
```

[minimal-repro](https://github.com/akielbowicz/vscode-binder/blob/test-code-server-on-postBuil/postBuild#L9)
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/akielbowicz/vscode-binder/test-code-server-on-postBuil?urlpath=vscode)
![image](https://user-images.githubusercontent.com/30580760/93692613-ce059980-facb-11ea-932a-74f8c8a71902.png)

Thanks a lot for this tool! It's pretty awesome to be able to do this, and extremely useful for teaching.

**Comment by xhochy** [comment]
This is no longer an issue with the latest BinderHub deployment.
