### ISSUE TITLE
Turn into package

### ISSUE THREAD

**Issue by xhochy** [betatim/vscode-binder#3]
This repo is really useful, although the amount of code in https://github.com/betatim/vscode-binder/tree/master/jupyter_vscode_proxy is still really small I would like to see this as a proper package. I would also volunteer to add some code to make the `code-server` call more configurable.

**Comment by betatim** [comment]
The ideal goal would be that people can `pip install vscode-proxy` (or something like that) and get all the things they need for it to just work in a container built by repo2docker or "any other" JupyterHub setup.

Not sure which one is less ambitious/easier to achieve first.

Maybe step one is to add a `setup.py` that installs the Python stuff and assumes the user already has `code-server` on the PATH already.

Probably also need a new name for the package. Maybe `jupyter-vscode-proxy` a la https://github.com/jupyterhub/jupyter-rsession-proxy? 

(all forms of PRs welcome)

**Comment by xhochy** [comment]
This is now available on PyPI and conda-forge, thanks!
