### ISSUE TITLE
running jupyter notebooks in vscode

### ISSUE THREAD

**Issue by rokroskar** [betatim/vscode-binder#9]
Very useful little extension! 

Curious if anyone has successfully run a jupyter notebook using the extension? Seems to be a bit of a mess of port conflicts, I'm not really sure where to start debugging.

**Comment by betatim** [comment]
I've never tried. Not even with a local VS code really. The one time I tried it imported the notebook and created a `.py` file from it which confused me. Does VS code start its own notebook server?

Would be good to have an example for how to do this.

**Comment by rokroskar** [comment]
Yeah it seems to. It complains about not being able to connect to port 8888 so it's probably just a matter of figuring out where to modify the flags. Ideally it could just connect to the already running jupyter server I suppose.

**Comment by psychemedia** [comment]
As described in the discourse thread [Official VSCode Instructions](https://github.com/Colorado-CompSci-Ugrad/csel-per-class-jupyter-containers), Uni of Colorado have Jupyter container builds [here](https://github.com/Colorado-CompSci-Ugrad/csel-per-class-jupyter-containers) that embeds VS Code and uses the [dirkcgrunwald/jupyter_codeserver_proxy-](https://github.com/dirkcgrunwald/jupyter_codeserver_proxy-).

I'm not sure how that set-up differs to the one described here?

**Comment by rokroskar** [comment]
This doesn't seem to be a problem anymore - not sure what has changed since the last time I tried but it works fine now. 

Note that for the moment the python extension with code-server is broken and it's necessary to install the previous version of the python extension _and_ disable automatic updates, so with something like

```
code-server --install-extension ms-python.python@2020.10.332292344
mkdir ~/.vscode && \
echo '{"extensions.autoCheckUpdates": false,"extensions.autoUpdate": false}' > ${HOME}/.vscode/argv.json
```

see https://github.com/cdr/code-server/issues/2298 and https://github.com/cdr/code-server/issues/2293

**Comment by rokroskar** [comment]
False alarm - they've since fixed the python extension in the code-server marketplace and everything works as expected 🎉
